### ISSUE TITLE
Unable to get feature info of other ObjectClasses, it always searching feature against Building which id is 26

### ISSUE THREAD

**Issue by SurajitChowbey** [3dcitydb/web-feature-service#1]
Unable to get feature info of other ObjectClass, it always searching feature against Building wihich id is 26.

Request body:
`<?xml version="1.0" encoding="UTF-8"?>
<wfs:GetFeature service="WFS" version="2.0.0" xmlns:wfs="http://www.opengis.net/wfs/2.0">
  <wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
    <wfs:Parameter name="id">UUID_51cf1f1d-5e9b-4e0f-ac57-ad5e84e6a524</wfs:Parameter>
  </wfs:StoredQuery>
</wfs:GetFeature>`

**Comment by clausnagel** [comment]
Per default, the WFS only advertises the CityGML `Building` feature type. If you want to query other feature types, then simply add them to the `config.xml` file and reload the config afterwards.

**Comment by SurajitChowbey** [comment]
Thanks, it working.
I have some queries,

1)	if want to explicitly specify the respective ObjectClass in the XML body, is there is a way to do that?
	As it will decrease the query execution time.

	ex: 
	`select  co.id, co.objectclass_id, count(1) over () as match_all from cityobject co where  co.objectclass_id in (26, 5)  and co.gmlid = ? order by co.id`

	above query will be then as following:

	`select  co.id, co.objectclass_id, count(1) over () as match_all from cityobject co where  co.objectclass_id in (5)  and co.gmlid = ? order by co.id`

2)	Is there is a way to limit the no of properties it will return by specifying which properties I want to be in the result or in any other way? 

Thanks for your time.

**Comment by clausnagel** [comment]
The current implementation of the 3DCityDB WFS only supports the `Simple WFS` conformance class (for more details see the [WFS specification](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html)).

This means that the `GetFeatureById` query is in fact the only supported operation for requesting features. And this query only takes the `gml:id` as parameter - it neither supports providing the requested feature types nor limiting the feature properties.

At my company [virtualcitySYSTEMS](http://www.virtualcitysystems.de/en/), we offer a much more sophisticated WFS implementation for the 3DCityDB, which provides the functionality you are looking for. Simply drop me an email if you are interested.

**Comment by clausnagel** [comment]
Closing this issue. Feel free to re-open if there are follow-up questions.
