### ISSUE TITLE
Docker multi-architecture support

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/web-feature-service#10]
Docker supports building images for multiple CPU architectures using [`docker buildx`](https://docs.docker.com/desktop/multi-arch/).
This is becoming more relevant, as for instance the new generation of MACs comes with `arm64` CPUs.

* [Announcement ARM MACs](https://www.heise.de/news/Apple-praesentiert-ARM-Mac-mit-Achtkernprozessor-4953652.html)
* [How to do this with Github actions](https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/)

**Comment by clausnagel** [comment]
There have been no requests for ARM images so far, so closing this issue.
