### ISSUE TITLE
Default CRS

### ISSUE THREAD

**Issue by mossgmbh-user** [3dcitydb/web-feature-service#13]
Hi

Testing our citydb-wfs installation with the [INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator/test-selection/index.html) produced the following error:

```
Error message: Default CRS not recognized. No authority was defined for code.
```
Our guess is, that the config.xml lacks the correct CRS info.

Which CRS info is necessary for featuretype with EPSG:25832?

Thanks a lot

**Comment by clausnagel** [comment]
So sorry that I only see this question now. In general, the CRS information that is put into a WFS response is taken from the `gml_srs_name` column of the `database_srs` table. This column is populated with the value entered when setting up the 3DCityDB instance. It can be changed later using the Importer/Exporter (https://3dcitydb-docs.readthedocs.io/en/latest/impexp/db-operations/db-change-crs.html).

Please note that CityGML 2.0/1.0 still uses GML 3.1.1 while the WFS 2.0 specification expects GML 3.2. So, depending on how strict this validator is that you are using, this might be a problem for validation anyway.
