### ISSUE TITLE
WFS Request

### ISSUE THREAD

**Issue by AndyLicht** [3dcitydb/web-feature-service#3]
Hi,
i want to test the WFS- functions of my 3dcitydb-Installation in combination with the wfs-tool.

I´m using the wfs- tool with the default configuration ( i only configured the database settings)
`<type>PostGIS</type>
      <server>127.0.0.1</server>
      <port>5432</port>
      <sid>dreid</sid>
      <schema/>
      <user>postgres</user>
      <password>passwd</password>`

When i send a capabilites or a describe feature type request it seems to work fine, but the GetFeature-Request only sends an error:

my tested URL:
http://localhost:8080/citydb-wfs/wfs?service=WFS&version=2.0.0&request=GetFeature&typeNames=bldg:Building

and my response:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd" version="2.0.0" xml:lang="en">
<ows:Exception exceptionCode="OptionNotSupported">
<ows:ExceptionText>
Only stored query expressions are supported in a GetFeature request.
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>`

With:
http://localhost:8080/citydb-wfs/wfs?service=WFS&version=2.0.0&request=ListStoredQueries

i get
`<wfs:ListStoredQueriesResponse xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
<wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
<wfs:Title xml:lang="en">Get feature by identifier</wfs:Title>
</wfs:StoredQuery>
</wfs:ListStoredQueriesResponse>`

so i´ve build a GetFeature-Request with a ID filter:
http://localhost:8080/citydb-wfs/wfs?service=WFS&version=2.0.0&request=GetFeature&typeNames=bldg:Building&featureID=feature

the response is also:
`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd" version="2.0.0" xml:lang="en">
<ows:Exception exceptionCode="OptionNotSupported">
<ows:ExceptionText>
Only stored query expressions are supported in a GetFeature request.
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>`

Can you show me an example to get all or one feature?
best regards

**Comment by clausnagel** [comment]
The WFS is implemented against the _Simple WFS_ conformance class. Thus, it currently only supports `GetFeature` requests with the stored query `GetFeatureById`. This is what the first error message in your post indicates.

A valid XML-encoded query for HTTP POST would like like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<wfs:GetFeature service="WFS" version="2.0.0" xmlns:wfs="http://www.opengis.net/wfs/2.0">
  <wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
    <wfs:Parameter name="id">ID_0815</wfs:Parameter>
  </wfs:StoredQuery>
</wfs:GetFeature>
```
You can also encode it using KVP over HTTP GET:
http://localhost:8080/citydb-wfs/wfs?service=WFS&version=2.0.0&request=GetFeature&storedquery_id=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fquery%2FOGC-WFS%2F0%2FGetFeatureById&id=ID_0815

You will find more information in chapter 7 of the documentation (see chapter 7.4.6 for the `GetFeature` operation).

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open.

**Comment by cbsemre** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<wfs:GetFeature service="WFS" version="2.0.0" xmlns:wfs="http://www.opengis.net/wfs/2.0">
  <wfs:StoredQuery id="http://www.opengis.net/def/query/OGC-WFS/0/GetFeatureById">
    <wfs:Parameter name="id">ID_0815</wfs:Parameter>
  </wfs:StoredQuery>
</wfs:GetFeature>

bu kodu config.xml dosyasına mı yazmamız gerekiyor. Vc Publisher ile CityGml verilerini sorgulamak için ?

// en

Do we need to write this code in the config.xml file? To question CityGml corruption with Vc Publisher?

**Comment by cbsemre** [comment]
<ows:Exception exceptionCode="OptionNotSupported"> <ows:ExceptionText>Only stored query expressions are supported in a GetFeature request.</ows:ExceptionText> </ows:Exception> </ows:ExceptionReport>
 
 // 
With Vc Publisher, the query process always stays that way. Where should we write the sample xml code to query the get feature?
//
 
 Vc Publisher ile sorgu yaptığım zaman bu hatayı alıyorum. Get feature ile il sorgulamak için örnek xml kodunu nereye yazmamız gerekiyor?

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/web-feature-service/assets/105004541/6f2b877f-2a9e-4112-865b-a21ea704371d)

### **get feature  işlemi için bu örnek kodu nereye yazmamız gerekiyor?**``

**Comment by clausnagel** [comment]
We do not provide support for VCS products like the VC Publisher here. Please contact the VCS support.
