### ISSUE TITLE
Changes in configuration (V4.0.0)?

### ISSUE THREAD

**Issue by sensor-freak** [3dcitydb/web-feature-service#4]
Hi,

I recently updated a 3DCityDB instance to V4.0.0, and therefore I had also to update the WFS. But now CreateStoredQuery and DropStoredQuery are no longer supported by WFS.

In the config file I have set "<ManageStoredQueries isEnabled="true"/>", as in the previous version of the WFS.

Did I miss something? Is management of stored queries still supported?

**Comment by clausnagel** [comment]
All previous versions have only supported the `ListStoredQueries` and `DescribeStoredQueries` operations so far. As documented in the README, the WFS currently only implements the Simple WFS conformance class. This might change in a future version.

Maybe you have been using a different WFS for the 3DCityDB?

**Comment by sensor-freak** [comment]
Yes, my fault. As explained otherwise I mixed it up with some other instance.
